server:
  port: 9002

logging:
  level:
    com.emo: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: nacos:8848

