POST localhost:8080/secret/user/list
Content-Type: application/json
signature: 55efb04a83ca083dd1e6003cde127c45
timestamp: 1648308048
salt: 123456
clientType: ANDORID


###
POST localhost:8080/secret/user/list
Content-Type: application/json





{
  "data": "BZphXKR35/p9iqelT/S68CuGxLPKdxMc2/ABA/J+jJGbk9T0d585Ers9hYAK6mspAwO///SCVG+m3zAmbmTcUqH9RBm/m9zGKqTvu/tkO3IZ8EdH+Z2+b0NVSsPkoXmyyGelgvonZXd0coLhEs4ksqSmamf8HgNALlJGmKVy/A9LtwmxzQi53vfMK6/Dlihu8LjcOsNY/C2f9KdHMTckZRvMkVw6Faend24BnTl/nkXHDqA8Bt5ZgeBTV8CJAbkfrVZKXcbPcDbsqDhDnhExUA==",
  "code": 200,
  "signature": "a0a6f34d4e0c40de35916d6aa0f7ddfa",
  "msg": "",
  "timestamp": 1659433977,
  "salt": 341249
}