server:
  port: 9001

logging:
  level:
    com.emo: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: nacos:8848
