docker run \
    --name mymysql \
    -p 3306:3306 \
    -v /tmp/mysql/data:/var/lib/mysql \
    -v /tmp/mysql/conf/hmy.cnf:/etc/mysql/conf.d/hmy.cnf \
    -e MYSQL_ROOT_PASSWORD=123456 \
    -d \
    mysql:5.7.25