version: "3.2"

services:
  nacos:
    image: nacos/nacos-server
    environment:
      MODE: standalone
      port:
        - "8848:8848"
  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "$PWD/mysql/data:/var/lib/mysql"
      - "$PWD/mysql/conf:/etc/mysql/conf.d"
    userservice:
      build: ./user-service
    orderservice:
      build: ./orderservice
    gateway:
      build: ./gateway
      ports:
        - "10010:10010"